services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: "api"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY_RECAPTCHA: ${SECRET_KEY_RECAPTCHA}
      GOOGLE_API_URL: ${GOOGLE_API_URL}
      PUPPETEER_EXECUTABLE_PATH: ${PUPPETEER_EXECUTABLE_PATH}
      SCRAPING_URL: ${SCRAPING_URL}
      SCRAPE_MODE: ${SCRAPE_MODE}
      IP_SUPPORT: ${IP_SUPPORT}
    networks:
      - connection_network
    depends_on:
      - postgres
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: "client"
    restart: unless-stopped
    environment:
      VITE_API_URL: ${VITE_API_URL}
      VITE_CAPTCHA_SITE_KEY: ${VITE_CAPTCHA_SITE_KEY}
    networks:
      - connection_network
    depends_on:
      - backend

  postgres:
    image: postgres:17-alpine
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - connection_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot-etc:/etc/letsencrypt
      - webroot:/var/www/html
      - ./frontend/dist:/usr/share/nginx/html
    networks:
      - connection_network
    depends_on:
      - backend
      - frontend
      - postgres

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - webroot:/var/www/html
    depends_on:
      - nginx
    command: sh -c "while :; do certbot renew; sleep 12h; done"

networks:
  connection_network:
    driver: bridge
volumes:
  pgdata:
  certbot-etc:
  certbot-var:
  webroot: