server {
    listen 80;
    server_name passportindex.live www.passportindex.live;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location /api/ {
        proxy_pass http://backend:5000;
    }

    location / {
        proxy_pass http://frontend:80;
    }
}