server {
    listen 80;
    server_name passportindex.live www.passportindex.live;

    # مهم جداً لعملية التجديد وإصدار الشهادة
    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        # تحويل حركة المرور إلى HTTP مؤقتاً لإصدار الشهادة
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}