# name: Deploy to VPS

# on:
#   push:
#     branches: [ main ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2

#       - name: Deploy to VPS
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.VPS_IP }}
#           username: ${{ secrets.VPS_USERNAME }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           port: ${{ secrets.PORT }}
#           script: |
#             cd ~/passportindex
#             git pull
#             docker compose down
#             docker compose up -d